@extends('users/layout')
@section('container')
 
<body>
<section>
        <div class="login pro-edit-update">
            <div class="container">
                <div class="alert alert-success">
                            {{session('message')}}
                            </div>
                <div class="row">

                    <div class="inn">
                        <div class="lhs">
                            <div class="tit">
                                <h2>Now <b>Find your Soul Mate</b> Easy and fast.</h2>
                            </div>
                            <div class="im">
                                <img src="https://tamilthirumanam.com/users_assets/images/login-couple.png" alt="">
                            </div>
                            <div class="tit">
                                
                                <h2><br><br><br>Now in<br><br><b>Partner info page</b> 4 more sections to go...</h2>
                                
                            </div>
                            <div class="log-bg">&nbsp;</div>
                        </div>
                        
                        <div class="rhs">
                            
                            
                                <div class="form-tit">
                                    <h4>Find Your Partner</h4>
                                    <h1>Partner Preferences</h1>
                                    
                                </div>
                                <div class="form-login">
                                    <form action="{{route('match_making.match_making_process')}}" method="post">
                                        @csrf
                                        <div class="row" style="display:none;">
                                            <div class="col-md-6 form-group">
                                                <label class="lb">ID:</label>
                                                @foreach($data as $list)
                                                <input type="text" class="form-control" 
                                                    name="paaid" value="{{$list->rand_id}}" readonly>
                                                <input type="text" class="form-control" 
                                                    name="mgender" value="{{$list->gender}}" readonly>
                                                    @endforeach
                                                </div>
                                            </div>
                                            <div class="row">
                                            <div class="col-md-6 form-group">
                                                <label class="lb">Caste:</label>
                                                <select type="text" class="form-control" name="mcaste" id="caste" required>
                                                <option value="">Select</option>
                                                <option value="24_Manai_Telugu_Chettiar">24 Manai Telugu Chettiar</option>
                                                <option value="96_Kuli_Maratha">96 Kuli Maratha</option>
                                                <option value="Aaru_Nattu_Vellala">Aaru Nattu Vellala</option>
                                                <option value="Achirapakkam_Chettiar">Achirapakkam Chettiar</option>
                                                <option value="Ad_Dharmi">Ad Dharmi</option>
                                                <option value="Adi_Andhra">Adi Andhra</option>
                                                <option value="Adi_Dravidar">Adi Dravidar</option>
                                                <option value="693">Adi Karnataka</option>
                                                <option value="935">Agamudayar / Arcot / Thuluva Vellala</option>
                                                <option value="891">Agaram Vellan Chettiar</option>
                                                <option value="3">Agarwal</option>
                                                <option value="4">Agnikula Kshatriya</option>
                                                <option value="862">Agrahari</option>
                                                <option value="5">Agri</option>
                                                <option value="1025">Aguri / Ugra Kshatriya</option>
                                                <option value="1034">Aheriya</option>
                                                <option value="741">Ahir Shimpi</option>
                                                <option value="977">Ahirwar</option>
                                                <option value="6">Ahom</option>
                                                <option value="7">Ambalavasi</option>
                                                <option value="181">Amil Sindhi </option>
                                                <option value="1038">Amma Kodava</option>
                                                <option value="260">Anavil Brahmin </option>
                                                <option value="839">Anjana (Chowdary) Patel</option>
                                                <option value="1010">Arakh / Arakvanshiya</option>
                                                <option value="800">Aramari / Gabit</option>
                                                <option value="294">Arekatica</option>
                                                <option value="281">Arora</option>
                                                <option value="8">Arunthathiyar</option>
                                                <option value="9">Arya Vysya</option>
                                                <option value="863">Asathi</option>
                                                <option value="261">Audichya Brahmin </option>
                                                <option value="892">Ayira Vysya</option>
                                                <option value="923">Ayodhyavasi</option>
                                                <option value="685">Ayyaraka</option>
                                                <option value="673">Badaga</option>
                                                <option value="698">Bagdi</option>
                                                <option value="182">Baibhand Sindhi</option>
                                                <option value="10">Baidya</option>
                                                <option value="2313">Bairagi</option>
                                                <option value="978">Bairwa</option>
                                                <option value="11">Baishnab</option>
                                                <option value="12">Baishya</option>
                                                <option value="699">Bajantri</option>
                                                <option value="979">Balai</option>
                                                <option value="13">Balija</option>
                                                <option value="742">Balija Naidu</option>
                                                <option value="755">Balija Reddy</option>
                                                <option value="700">Banayat Oriya</option>
                                                <option value="14">Banik</option>
                                                <option value="15">Baniya</option>
                                                <option value="701">Baniya - Bania</option>
                                                <option value="702">Baniya - Kumuti</option>
                                                <option value="295">Banjara</option>
                                                <option value="2314">Baori</option>
                                                <option value="296">Barai</option>
                                                <option value="254">Barendra Brahmin </option>
                                                <option value="2315">Bargi</option>
                                                <option value="297">Bari</option>
                                                <option value="703">Baria</option>
                                                <option value="864">Barnwal</option>
                                                <option value="16">Barujibi</option>
                                                <option value="2316">Bavaria</option>
                                                <option value="2317">Bazigar</option>
                                                <option value="2318">Beldar</option>
                                                <option value="893">Beri Chettiar</option>
                                                <option value="17">Besta</option>
                                                <option value="2319">Bhand</option>
                                                <option value="18">Bhandari</option>
                                                <option value="183">Bhanusali Sindhi </option>
                                                <option value="2344">Bhar</option>
                                                <option value="2345">Bharbhunja</option>
                                                <option value="19">Bhatia</option>
                                                <option value="184">Bhatia Sindhi </option>
                                                <option value="298">Bhatraju</option>
                                                <option value="267">Bhatt Brahmin </option>
                                                <option value="20">Bhavasar Kshatriya</option>
                                                <option value="1031">Bhil</option>
                                                <option value="704">Bhoi</option>
                                                <option value="21">Bhovi</option>
                                                <option value="737">Bhoyar</option>
                                                <option value="1014">Bhulia / Meher</option>
                                                <option value="240">Bhumihar Brahmin </option>
                                                <option value="22">Billava</option>
                                                <option value="2346">Bind</option>
                                                <option value="690">Bishnoi/Vishnoi</option>
                                                <option value="705">Bondili</option>
                                                <option value="23">Boyar</option>
                                                <option value="1028">Brahmakshtriya</option>
                                                <option value="24">Brahmbatt</option>
                                                <option value="260">Brahmin - Anavil</option>
                                                <option value="823">Brahmin - Anaviln Desai</option>
                                                <option value="261">Brahmin - Audichya</option>
                                                <option value="2320">Brahmin - Bagra</option>
                                                <option value="834">Brahmin - Baidhiki/Vaidhiki</option>
                                                <option value="2321">Brahmin - Baragaon</option>
                                                <option value="943">Brahmin - Bardai</option>
                                                <option value="254">Brahmin - Barendra</option>
                                                <option value="944">Brahmin - Bhargav</option>
                                                <option value="267">Brahmin - Bhatt</option>
                                                <option value="2322">Brahmin - Bhojak</option>
                                                <option value="240">Brahmin - Bhumihar</option>
                                                <option value="2323">Brahmin - Chaubisa</option>
                                                <option value="762">Brahmin - Dadhich</option>
                                                <option value="269">Brahmin - Daivadnya</option>
                                                <option value="2324">Brahmin - Dakaut</option>
                                                <option value="286">Brahmin - Danua</option>
                                                <option value="270">Brahmin - Deshastha</option>
                                                <option value="290">Brahmin - Dhiman</option>
                                                <option value="291">Brahmin - Dravida</option>
                                                <option value="734">Brahmin - Embrandiri</option>
                                                <option value="245">Brahmin - Garhwali</option>
                                                <option value="242">Brahmin - Gaur</option>
                                                <option value="262">Brahmin - Goswami/Gosavi</option>
                                                <option value="680">Brahmin - Gujar Gaur</option>
                                                <option value="26">Brahmin - Gurukkal</option>
                                                <option value="287">Brahmin - Halua</option>
                                                <option value="271">Brahmin - Havyaka</option>
                                                <option value="272">Brahmin - Hoysala</option>
                                                <option value="27">Brahmin - Iyengar</option>
                                                <option value="28">Brahmin - Iyer</option>
                                                <option value="299">Brahmin - Jangid</option>
                                                <option value="288">Brahmin - Jhadua</option>
                                                <option value="707">Brahmin - Jyotish</option>
                                                <option value="241">Brahmin - Kanyakubj</option>
                                                <option value="273">Brahmin - Karhade</option>
                                                <option value="945">Brahmin - Khadayata</option>
                                                <option value="706">Brahmin - Khandelwal</option>
                                                <option value="835">Brahmin - Khedaval</option>
                                                <option value="283">Brahmin - Kokanastha</option>
                                                <option value="274">Brahmin - Kota</option>
                                                <option value="763">Brahmin - Koteshwara / Kota (Madhwa )</option>
                                                <option value="255">Brahmin - Kulin</option>
                                                <option value="248">Brahmin - Kumaoni</option>
                                                <option value="275">Brahmin - Madhwa</option>
                                                <option value="243">Brahmin - Maithil</option>
                                                <option value="946">Brahmin - Mevada</option>
                                                <option value="263">Brahmin - Modh</option>
                                                <option value="282">Brahmin - Mohyal</option>
                                                <option value="264">Brahmin - Nagar</option>
                                                <option value="258">Brahmin - Namboodiri</option>
                                                <option value="332">Brahmin - Narmadiya </option>
                                                <option value="292">Brahmin - Niyogi</option>
                                                <option value="25">Brahmin - Others</option>
                                                <option value="694">Brahmin - Paliwal</option>
                                                <option value="289">Brahmin - Panda</option>
                                                <option value="246">Brahmin - Pandit</option>
                                                <option value="962">Brahmin - Panicker</option>
                                                <option value="708">Brahmin - Pareek</option>
                                                <option value="337">Brahmin - Pushkarna</option>
                                                <option value="947">Brahmin - Rajgor</option>
                                                <option value="256">Brahmin - Rarhi</option>
                                                <option value="832">Brahmin - Rarhi/Radhi</option>
                                                <option value="284">Brahmin - Rigvedi</option>
                                                <option value="257">Brahmin - Rudraj</option>
                                                <option value="268">Brahmin - Sakaldwipi</option>
                                                <option value="247">Brahmin - Sanadya</option>
                                                <option value="276">Brahmin - Sanketi</option>
                                                <option value="259">Brahmin - Saraswat</option>
                                                <option value="948">Brahmin - Sarua</option>
                                                <option value="244">Brahmin - Saryuparin</option>
                                                <option value="764">Brahmin - Shivalli (Madhva)</option>
                                                <option value="277">Brahmin - Shivhalli</option>
                                                <option value="827">Brahmin - Shri Gaud</option>
                                                <option value="942">Brahmin - Shri Mali</option>
                                                <option value="265">Brahmin - Shrimali</option>
                                                <option value="765">Brahmin - Shukla Yajurvedi</option>
                                                <option value="681">Brahmin - Sikhwal</option>
                                                <option value="278">Brahmin - Smartha</option>
                                                <option value="279">Brahmin - Sri Vaishnava</option>
                                                <option value="280">Brahmin - Stanika</option>
                                                <option value="949">Brahmin - Tapodhan</option>
                                                <option value="249">Brahmin - Tyagi</option>
                                                <option value="285">Brahmin - Vaidiki</option>
                                                <option value="687">Brahmin - Vaikhanasa</option>
                                                <option value="950">Brahmin - Valam</option>
                                                <option value="354">Brahmin - Velanadu</option>
                                                <option value="266">Brahmin - Vyas</option>
                                                <option value="951">Brahmin - Zalora</option>
                                                <option value="731">Brahmin Jijhotia </option>
                                                <option value="733">Brahmin Malviya </option>
                                                <option value="709">Brajastha Maithil</option>
                                                <option value="178">Bunt (Shetty)</option>
                                                <option value="37">CKP</option>
                                                <option value="1042">Chakkala Nair</option>
                                                <option value="738">Chalawadi and Holeya</option>
                                                <option value="30">Chambhar</option>
                                                <option value="31">Chandravanshi Kahar</option>
                                                <option value="1026">Charan</option>
                                                <option value="32">Chasa</option>
                                                <option value="339">Chattada Sri Vaishnava </option>
                                                <option value="924">Chaturth</option>
                                                <option value="33">Chaudary</option>
                                                <option value="34">Chaurasia</option>
                                                <option value="711">Chennadasar</option>
                                                <option value="965">Cherakula Vellalar</option>
                                                <option value="2347">Chero</option>
                                                <option value="35">Chettiar</option>
                                                <option value="185">Chhapru Sindhi </option>
                                                <option value="36">Chhetri</option>
                                                <option value="301">Chippolu (Mera)</option>
                                                <option value="880">Choudhary</option>
                                                <option value="38">Coorgi</option>
                                                <option value="186">Dadu Sindhi </option>
                                                <option value="269">Daivadnya Brahmin </option>
                                                <option value="286">Danua Brahmin </option>
                                                <option value="129">Darji </option>
                                                <option value="1062">Dasapalanjika / Kannada Saineegar</option>
                                                <option value="270">Deshastha Brahmin </option>
                                                <option value="801">Deshmukh</option>
                                                <option value="840">Desikar</option>
                                                <option value="844">Desikar Thanjavur</option>
                                                <option value="39">Devadiga</option>
                                                <option value="40">Devandra Kula Vellalar</option>
                                                <option value="41">Devang Koshthi</option>
                                                <option value="42">Devanga</option>
                                                <option value="886">Devanga Chettiar</option>
                                                <option value="135">Devar/Thevar/Mukkulathor</option>
                                                <option value="740">Devrukhe Brahmin</option>
                                                <option value="2325">Dhakad</option>
                                                <option value="980">Dhanak</option>
                                                <option value="43">Dhangar</option>
                                                <option value="2326">Dhanka</option>
                                                <option value="2312">Dhanuk</option>
                                                <option value="44">Dheevara</option>
                                                <option value="45">Dhiman</option>
                                                <option value="290">Dhiman Brahmin </option>
                                                <option value="46">Dhoba</option>
                                                <option value="732">Dhor / Kakkayya</option>
                                                <option value="712">Dommala</option>
                                                <option value="865">Dosar / Dusra</option>
                                                <option value="291">Dravida Brahmin </option>
                                                <option value="302">Dumal</option>
                                                <option value="303">Dusadh (Paswan)</option>
                                                <option value="48">Ediga</option>
                                                <option value="743">Ediga /Goud (Balija)</option>
                                                <option value="894">Elur Chetty</option>
                                                <option value="734">Embrandiri Brahmin </option>
                                                <option value="49">Ezhava</option>
                                                <option value="775">Ezhava Panicker</option>
                                                <option value="776">Ezhava Thandan</option>
                                                <option value="50">Ezhuthachan</option>
                                                <option value="51">Gabit</option>
                                                <option value="866">Gahoi</option>
                                                <option value="744">Gajula / Kavarai</option>
                                                <option value="684">Ganda</option>
                                                <option value="881">Gandha Vanika</option>
                                                <option value="2348">Gandharb</option>
                                                <option value="52">Gandla</option>
                                                <option value="768">Gandla / Ganiga</option>
                                                <option value="53">Ganiga</option>
                                                <option value="54">Garhwali</option>
                                                <option value="245">Garhwali Brahmin </option>
                                                <option value="2327">Garo / Garoda</option>
                                                <option value="713">Gatti</option>
                                                <option value="242">Gaur Brahmin </option>
                                                <option value="1013">Gavandi</option>
                                                <option value="55">Gavara</option>
                                                <option value="2328">Gavaria</option>
                                                <option value="304">Gawali</option>
                                                <option value="305">Ghisadi</option>
                                                <option value="56">Ghumar</option>
                                                <option value="57">Goala</option>
                                                <option value="58">Goan</option>
                                                <option value="306">Gomantak</option>
                                                <option value="1024">Gond</option>
                                                <option value="307">Gondhali</option>
                                                <option value="1055">Gopal / Gopala</option>
                                                <option value="262">Goswami/Gosavi Brahmin </option>
                                                <option value="250">Goud</option>
                                                <option value="59">Gounder</option>
                                                <option value="777">Gounder - Kongu Vellala Gounder</option>
                                                <option value="778">Gounder - Nattu Gounder</option>
                                                <option value="904">Gounder - Others</option>
                                                <option value="779">Gounder - Urali Gounder</option>
                                                <option value="780">Gounder - Vanniya Kula Kshatriyar</option>
                                                <option value="781">Gounder - Vettuva Gounder</option>
                                                <option value="60">Gowda</option>
                                                <option value="782">Gowda - Kuruba Gowda</option>
                                                <option value="308">Gramani</option>
                                                <option value="61">Gudia</option>
                                                <option value="680">Gujar Gaur Brahmin </option>
                                                <option value="310">Gujjar</option>
                                                <option value="925">Gulahre</option>
                                                <option value="62">Gupta</option>
                                                <option value="311">Guptan</option>
                                                <option value="309">Gurav</option>
                                                <option value="312">Gurjar</option>
                                                <option value="26">Gurukkal Brahmin </option>
                                                <option value="792">Haihaivanshi</option>
                                                <option value="714">Halba Koshti</option>
                                                <option value="287">Halua Brahmin </option>
                                                <option value="271">Havyaka Brahmin </option>
                                                <option value="1040">Heggade</option>
                                                <option value="715">Helava</option>
                                                <option value="1048">Holar</option>
                                                <option value="272">Hoysala Brahmin </option>
                                                <option value="313">Hugar (Jeer)</option>
                                                <option value="187">Hyderabadi Sindhi </option>
                                                <option value="966">Illaththu Pillai</option>
                                                <option value="63">Intercaste</option>
                                                <option value="64">Irani</option>
                                                <option value="936">Isai Vellalar</option>
                                                <option value="27">Iyengar Brahmin </option>
                                                <option value="28">Iyer Brahmin </option>
                                                <option value="314">Jaalari</option>
                                                <option value="65">Jaiswal</option>
                                                <option value="315">Jandra</option>
                                                <option value="66">Jangam</option>
                                                <option value="299">Jangid Brahmin </option>
                                                <option value="316">Jangra - Brahmin</option>
                                                <option value="67">Jat</option>
                                                <option value="29">Jatav</option>
                                                <option value="313">Jeer </option>
                                                <option value="716">Jetty/Malla</option>
                                                <option value="802">Jhadav</option>
                                                <option value="288">Jhadua Brahmin </option>
                                                <option value="731">Jijhotia Brahmin</option>
                                                <option value="2329">Jingar</option>
                                                <option value="317">Jogi (Nath)</option>
                                                <option value="981">Julaha</option>
                                                <option value="318">Kachara</option>
                                                <option value="251">Kadava Patel</option>
                                                <option value="1030">Kadia</option>
                                                <option value="691">Kahar</option>
                                                <option value="68">Kaibarta</option>
                                                <option value="955">Kaikaala</option>
                                                <option value="695">Kalal</option>
                                                <option value="739">Kalanji</option>
                                                <option value="69">Kalar</option>
                                                <option value="2330">Kalbelia</option>
                                                <option value="70">Kalinga</option>
                                                <option value="319">Kalinga Vysya</option>
                                                <option value="71">Kalita</option>
                                                <option value="72">Kalwar</option>
                                                <option value="73">Kamboj</option>
                                                <option value="74">Kamma</option>
                                                <option value="816">Kamma Naidu</option>
                                                <option value="982">Kanakkan Padanna</option>
                                                <option value="983">Kandara</option>
                                                <option value="2331">Kandera</option>
                                                <option value="2332">Kanjar</option>
                                                <option value="75">Kansari</option>
                                                <option value="1035">Kansyakaar</option>
                                                <option value="241">Kanyakubj Brahmin </option>
                                                <option value="783">Kanykubj Bania</option>
                                                <option value="76">Kapu</option>
                                                <option value="785">Kapu Naidu</option>
                                                <option value="928">Kapu Reddy</option>
                                                <option value="956">Karakala Bhakthula</option>
                                                <option value="77">Karana</option>
                                                <option value="273">Karhade Brahmin </option>
                                                <option value="841">Karkathar</option>
                                                <option value="78">Karmakar</option>
                                                <option value="957">Karni Bhakthula</option>
                                                <option value="79">Karuneegar</option>
                                                <option value="80">Kasar</option>
                                                <option value="867">Kasaundhan</option>
                                                <option value="2376">Kasera</option>
                                                <option value="81">Kashyap</option>
                                                <option value="895">Kasukara</option>
                                                <option value="320">Katiya</option>
                                                <option value="750">Kavara</option>
                                                <option value="717">Kavuthiyya/Ezhavathy</option>
                                                <option value="82">Kayastha</option>
                                                <option value="787">Kayastha (Bengali)</option>
                                                <option value="938">Kerala Mudali</option>
                                                <option value="868">Keshri (Kesarwani)</option>
                                                <option value="83">Khandayat</option>
                                                <option value="84">Khandelwal</option>
                                                <option value="718">Kharwa</option>
                                                <option value="321">Kharwar</option>
                                                <option value="984">Khatik</option>
                                                <option value="85">Khatri</option>
                                                <option value="719">Kirar</option>
                                                <option value="1041">Kodava</option>
                                                <option value="968">Kodikal Pillai</option>
                                                <option value="326">Koiri </option>
                                                <option value="283">Kokanastha Brahmin </option>
                                                <option value="322">Kokanastha Maratha</option>
                                                <option value="2333">Kokna</option>
                                                <option value="86">Koli</option>
                                                <option value="689">Koli Mahadev</option>
                                                <option value="720">Koli Patel</option>
                                                <option value="757">Komti /Arya Vaishya</option>
                                                <option value="896">Kongu Chettiar</option>
                                                <option value="813">Kongu Nadar</option>
                                                <option value="87">Kongu Vellala Gounder</option>
                                                <option value="88">Konkani</option>
                                                <option value="721">Korama</option>
                                                <option value="89">Kori</option>
                                                <option value="849">Kori/Koli</option>
                                                <option value="722">Kosthi</option>
                                                <option value="274">Kota Brahmin </option>
                                                <option value="723">Krishnavaka</option>
                                                <option value="90">Kshatriya</option>
                                                <option value="793">Kshatriya Kurmi</option>
                                                <option value="929">Kshatriya Raju</option>
                                                <option value="91">Kudumbi</option>
                                                <option value="92">Kulal</option>
                                                <option value="93">Kulalar</option>
                                                <option value="255">Kulin Brahmin </option>
                                                <option value="94">Kulita</option>
                                                <option value="248">Kumaoni Brahmin </option>
                                                <option value="974">Kumaoni Rajput</option>
                                                <option value="323">Kumawat</option>
                                                <option value="95">Kumbhakar</option>
                                                <option value="96">Kumbhar</option>
                                                <option value="97">Kumhar</option>
                                                <option value="98">Kummari</option>
                                                <option value="99">Kunbi</option>
                                                <option value="804">Kunbi Lonari</option>
                                                <option value="805">Kunbi Maratha</option>
                                                <option value="806">Kunbi Tirale</option>
                                                <option value="324">Kuravan</option>
                                                <option value="325">Kurmi</option>
                                                <option value="100">Kurmi/Kurmi Kshatriya</option>
                                                <option value="958">Kurni</option>
                                                <option value="101">Kuruba</option>
                                                <option value="102">Kuruhina Shetty</option>
                                                <option value="887">Kuruhini Chetty</option>
                                                <option value="103">Kurumbar</option>
                                                <option value="850">Kuruva</option>
                                                <option value="326">Kushwaha (Koiri)</option>
                                                <option value="104">Kutchi</option>
                                                <option value="882">Lad</option>
                                                <option value="2377">Lakhara / Lakhera / Laxkar</option>
                                                <option value="105">Lambadi</option>
                                                <option value="188">Larai Sindhi </option>
                                                <option value="189">Larkana Sindhi </option>
                                                <option value="1056">Laxminarayan gola</option>
                                                <option value="252">Leva patel</option>
                                                <option value="253">Leva patil</option>
                                                <option value="751">Linga Balija</option>
                                                <option value="106">Lingayath</option>
                                                <option value="327">Lodhi Rajput</option>
                                                <option value="107">Lohana</option>
                                                <option value="190">Lohana Sindhi </option>
                                                <option value="677">Lohar</option>
                                                <option value="724">Loniya</option>
                                                <option value="108">Lubana</option>
                                                <option value="759">Madhesiya/Kanu/Halwai</option>
                                                <option value="275">Madhwa Brahmin </option>
                                                <option value="109">Madiga</option>
                                                <option value="47">Madivala / Dhobi</option>
                                                <option value="110">Mahajan</option>
                                                <option value="111">Mahar</option>
                                                <option value="112">Mahendra</option>
                                                <option value="113">Maheshwari</option>
                                                <option value="869">Maheshwari / Meshri</option>
                                                <option value="114">Mahishya</option>
                                                <option value="926">Mahor</option>
                                                <option value="870">Mahuri</option>
                                                <option value="975">Mair Rajput Swarnkar</option>
                                                <option value="243">Maithil Brahmin </option>
                                                <option value="115">Majabi</option>
                                                <option value="116">Mala</option>
                                                <option value="117">Mali</option>
                                                <option value="118">Mallah</option>
                                                <option value="733">Malviya Brahmin</option>
                                                <option value="807">Malwani</option>
                                                <option value="119">Mangalorean</option>
                                                <option value="120">Manipuri</option>
                                                <option value="897">Manjapudur Chettiar</option>
                                                <option value="1045">Mannadiyar</option>
                                                <option value="985">Mannan / Velan / Vannan</option>
                                                <option value="122">Mapila</option>
                                                <option value="123">Maratha</option>
                                                <option value="803">Maratha Kshatriya</option>
                                                <option value="124">Maruthuvar</option>
                                                <option value="125">Matang</option>
                                                <option value="328">Mathur</option>
                                                <option value="927">Mathur Vaishya</option>
                                                <option value="1029">Matia Patel</option>
                                                <option value="735">Maurya / Shakya</option>
                                                <option value="126">Meena</option>
                                                <option value="127">Meenavar</option>
                                                <option value="986">Meghwal</option>
                                                <option value="2334">Mehar</option>
                                                <option value="128">Mehra</option>
                                                <option value="301">Mera </option>
                                                <option value="129">Meru Darji</option>
                                                <option value="130">Mochi</option>
                                                <option value="131">Modak</option>
                                                <option value="263">Modh Brahmin </option>
                                                <option value="1016">Modh Ghanchi</option>
                                                <option value="883">Modi</option>
                                                <option value="767">Modikarlu</option>
                                                <option value="132">Mogaveera</option>
                                                <option value="282">Mohyal Brahmin </option>
                                                <option value="133">Mudaliyar</option>
                                                <option value="134">Mudiraj</option>
                                                <option value="135">Mukkulathor </option>
                                                <option value="121">Munnuru Kapu</option>
                                                <option value="2349">Musahar</option>
                                                <option value="752">Musukama</option>
                                                <option value="136">Muthuraja / Mutharaiyar</option>
                                                <option value="329">Naagavamsam</option>
                                                <option value="761">Nabit</option>
                                                <option value="137">Nadar</option>
                                                <option value="264">Nagar Brahmin </option>
                                                <option value="330">Nagaralu</option>
                                                <option value="138">Nai / Nayi Brahmin</option>
                                                <option value="139">Naicker</option>
                                                <option value="939">Naicker - Others</option>
                                                <option value="814">Naicker - Vanniya Kula Kshatriyar</option>
                                                <option value="140">Naidu</option>
                                                <option value="141">Naik</option>
                                                <option value="343">Naika </option>
                                                <option value="142">Nair</option>
                                                <option value="143">Namasudra / Namassej</option>
                                                <option value="331">Nambiar</option>
                                                <option value="258">Namboodiri Brahmin </option>
                                                <option value="753">Namdarlu</option>
                                                <option value="969">Nanjil Mudali</option>
                                                <option value="1007">Nanjil Nattu Vellalar</option>
                                                <option value="1008">Nanjil Vellalar</option>
                                                <option value="973">Nanjil pillai</option>
                                                <option value="970">Nankudi Vellalar</option>
                                                <option value="144">Napit</option>
                                                <option value="332">Narmadiya Brahmin </option>
                                                <option value="2335">Nat</option>
                                                <option value="317">Nath </option>
                                                <option value="788">Nattu Gounder</option>
                                                <option value="898">Nattukottai Chettiar</option>
                                                <option value="145">Nayaka</option>
                                                <option value="333">Neeli</option>
                                                <option value="959">Neeli Saali</option>
                                                <option value="871">Nema</option>
                                                <option value="146">Nepali</option>
                                                <option value="960">Nessi</option>
                                                <option value="147">Nhavi</option>
                                                <option value="1053">Niari</option>
                                                <option value="292">Niyogi Brahmin </option>
                                                <option value="1046">Odan</option>
                                                <option value="786">Ontari</option>
                                                <option value="1009">Oraon</option>
                                                <option value="148">Oswal</option>
                                                <option value="334">Otari</option>
                                                <option value="842">Othuvaar</option>
                                                <option value="149">Padmasali</option>
                                                <option value="888">Padmashali</option>
                                                <option value="884">Padmavati Porwal</option>
                                                <option value="754">Pagadala</option>
                                                <option value="150">Pal</option>
                                                <option value="845">Pallan / Devandra Kula Vellalan</option>
                                                <option value="987">Panan</option>
                                                <option value="151">Panchal</option>
                                                <option value="289">Panda Brahmin </option>
                                                <option value="688">Pandaram</option>
                                                <option value="246">Pandit Brahmin </option>
                                                <option value="971">Pandiya Vellalar</option>
                                                <option value="152">Panicker</option>
                                                <option value="899">Pannirandam Chettiar</option>
                                                <option value="988">Paravan / Bharatar</option>
                                                <option value="933">Parit</option>
                                                <option value="153">Parkavakulam / Udayar</option>
                                                <option value="154">Parsi</option>
                                                <option value="335">Partraj</option>
                                                <option value="769">Parvatha Rajakulam</option>
                                                <option value="155">Pasi</option>
                                                <option value="303">Paswan </option>
                                                <option value="976">Paswan / Dusadh</option>
                                                <option value="156">Patel</option>
                                                <option value="676">Pathare Prabhu</option>
                                                <option value="808">Patil</option>
                                                <option value="157">Patnaick/Sistakaranam</option>
                                                <option value="158">Patra</option>
                                                <option value="770">Pattinavar</option>
                                                <option value="889">Pattusali</option>
                                                <option value="872">Patwa</option>
                                                <option value="336">Perika</option>
                                                <option value="790">Perika/Puragiri Kshatriya</option>
                                                <option value="159">Pillai</option>
                                                <option value="1011">Poddar</option>
                                                <option value="683">Poosala</option>
                                                <option value="160">Porwal</option>
                                                <option value="873">Porwal / Porwar</option>
                                                <option value="989">Poundra</option>
                                                <option value="161">Prajapati</option>
                                                <option value="990">Pulaya / Cheruman</option>
                                                <option value="337">Pushkarna Brahmin </option>
                                                <option value="2336">Rabari</option>
                                                <option value="1057">Radhi / Niari</option>
                                                <option value="358">Raigar</option>
                                                <option value="162">Rajaka / Vannar</option>
                                                <option value="163">Rajastani</option>
                                                <option value="686">Rajbhar</option>
                                                <option value="164">Rajbonshi</option>
                                                <option value="725">Rajpurohit</option>
                                                <option value="165">Rajput</option>
                                                <option value="1054">Raju / Kshatriya Raju</option>
                                                <option value="726">Ramanandi</option>
                                                <option value="166">Ramdasia</option>
                                                <option value="167">Ramgariah</option>
                                                <option value="727">Ramoshi</option>
                                                <option value="256">Rarhi Brahmin </option>
                                                <option value="874">Rastogi</option>
                                                <option value="885">Rathi</option>
                                                <option value="875">Rauniar</option>
                                                <option value="2337">Ravana Rajput</option>
                                                <option value="168">Ravidasia</option>
                                                <option value="169">Rawat</option>
                                                <option value="170">Reddy</option>
                                                <option value="338">Relli</option>
                                                <option value="284">Rigvedi Brahmin </option>
                                                <option value="191">Rohiri Sindhi </option>
                                                <option value="851">Rohit / Chamar</option>
                                                <option value="728">Ror</option>
                                                <option value="257">Rudraj Brahmin </option>
                                                <option value="176">SC</option>
                                                <option value="197">SKP</option>
                                                <option value="214">ST</option>
                                                <option value="171">Sadgope</option>
                                                <option value="771">Sadhu Chetty</option>
                                                <option value="215">Sagara (Uppara)</option>
                                                <option value="172">Saha</option>
                                                <option value="2338">Sahariya</option>
                                                <option value="192">Sahiti Sindhi </option>
                                                <option value="173">Sahu</option>
                                                <option value="174">Saini</option>
                                                <option value="843">Saiva Pillai Thanjavur</option>
                                                <option value="810">Saiva Pillai Tirunelveli</option>
                                                <option value="1012">Saiva Vellan chettiar</option>
                                                <option value="268">Sakaldwipi Brahmin </option>
                                                <option value="193">Sakkhar Sindhi </option>
                                                <option value="175">Saliya</option>
                                                <option value="1061">Saliyar</option>
                                                <option value="2339">Salvi</option>
                                                <option value="991">Samagar</option>
                                                <option value="852">Sambava</option>
                                                <option value="247">Sanadya Brahmin </option>
                                                <option value="276">Sanketi Brahmin </option>
                                                <option value="2340">Sansi</option>
                                                <option value="259">Saraswat Brahmin </option>
                                                <option value="2341">Sargara</option>
                                                <option value="244">Saryuparin Brahmin </option>
                                                <option value="736">Sathwara</option>
                                                <option value="992">Satnami</option>
                                                <option value="340">Savji</option>
                                                <option value="194">Sehwani Sindhi </option>
                                                <option value="177">Senai Thalaivar</option>
                                                <option value="341">Senguntha Mudaliyar</option>
                                                <option value="811">Sengunthar/Kaikolar</option>
                                                <option value="293">Settibalija</option>
                                                <option value="748">Setty Balija</option>
                                                <option value="1027">Shah</option>
                                                <option value="760">Shaw / Sahu/Teli</option>
                                                <option value="961">Shettigar</option>
                                                <option value="178">Shetty </option>
                                                <option value="195">Shikarpuri Sindhi </option>
                                                <option value="993">Shilpkar</option>
                                                <option value="179">Shimpi/Namdev</option>
                                                <option value="277">Shivhalli Brahmin </option>
                                                <option value="265">Shrimali Brahmin </option>
                                                <option value="681">Sikhwal Brahmin </option>
                                                <option value="180">Sindhi</option>
                                                <option value="181">Sindhi-Amil</option>
                                                <option value="182">Sindhi-Baibhand</option>
                                                <option value="183">Sindhi-Bhanusali</option>
                                                <option value="184">Sindhi-Bhatia</option>
                                                <option value="185">Sindhi-Chhapru</option>
                                                <option value="186">Sindhi-Dadu</option>
                                                <option value="187">Sindhi-Hyderabadi</option>
                                                <option value="188">Sindhi-Larai</option>
                                                <option value="189">Sindhi-Larkana</option>
                                                <option value="190">Sindhi-Lohana</option>
                                                <option value="191">Sindhi-Rohiri</option>
                                                <option value="192">Sindhi-Sahiti</option>
                                                <option value="193">Sindhi-Sakkhar</option>
                                                <option value="194">Sindhi-Sehwani</option>
                                                <option value="195">Sindhi-Shikarpuri</option>
                                                <option value="196">Sindhi-Thatai</option>
                                                <option value="2342">Sirvi / Janwa</option>
                                                <option value="278">Smartha Brahmin </option>
                                                <option value="198">Sonar</option>
                                                <option value="2343">Sondhia</option>
                                                <option value="199">Soni</option>
                                                <option value="994">Sonkar</option>
                                                <option value="200">Sourashtra</option>
                                                <option value="900">Sozhia Chetty</option>
                                                <option value="342">Sozhiya Vellalar</option>
                                                <option value="279">Sri Vaishnava Brahmin </option>
                                                <option value="682">Srisayana</option>
                                                <option value="280">Stanika Brahmin </option>
                                                <option value="343">Sugali (Naika)</option>
                                                <option value="344">Sunari</option>
                                                <option value="201">Sundhi</option>
                                                <option value="729">Surya Balija</option>
                                                <option value="202">Suthar</option>
                                                <option value="954">Swakula Saali</option>
                                                <option value="203">Swakula Sali</option>
                                                <option value="1023">Swarnakar</option>
                                                <option value="204">Tamboli</option>
                                                <option value="1063">Tammali</option>
                                                <option value="205">Tanti</option>
                                                <option value="206">Tantubai</option>
                                                <option value="207">Telaga</option>
                                                <option value="208">Teli</option>
                                                <option value="772">Telugupatti</option>
                                                <option value="209">Thakkar</option>
                                                <option value="675">Thakore</option>
                                                <option value="210">Thakur</option>
                                                <option value="995">Thandan</option>
                                                <option value="1044">Tharakan</option>
                                                <option value="196">Thatai Sindhi </option>
                                                <option value="211">Thigala</option>
                                                <option value="212">Thiyya</option>
                                                <option value="758">Thiyya Thandan</option>
                                                <option value="791">Thogata Veera Kshatriya</option>
                                                <option value="836">Thogata Veerakshathriya</option>
                                                <option value="812">Thondai Mandala Vellalar</option>
                                                <option value="756">Thota</option>
                                                <option value="213">Tili</option>
                                                <option value="2350">Tiyar/Tiar</option>
                                                <option value="346">Togata</option>
                                                <option value="347">Tonk Kshatriya</option>
                                                <option value="348">Turupu Kapu</option>
                                                <option value="249">Tyagi Brahmin </option>
                                                <option value="876">Ummar / Umre / Bagaria</option>
                                                <option value="696">Urali Gounder</option>
                                                <option value="349">Urs</option>
                                                <option value="356">Vada Balija</option>
                                                <option value="901">Vadambar</option>
                                                <option value="1050">Vadar</option>
                                                <option value="216">Vaddera</option>
                                                <option value="818">Vadugan</option>
                                                <option value="285">Vaidiki Brahmin </option>
                                                <option value="687">Vaikhanasa Brahmin </option>
                                                <option value="217">Vaish</option>
                                                <option value="218">Vaishnav</option>
                                                <option value="853">Vaishnav Dishaval</option>
                                                <option value="854">Vaishnav Kapol</option>
                                                <option value="855">Vaishnav Khadyata</option>
                                                <option value="856">Vaishnav Lad</option>
                                                <option value="857">Vaishnav Modh</option>
                                                <option value="858">Vaishnav Porvad</option>
                                                <option value="859">Vaishnav Shrimali</option>
                                                <option value="860">Vaishnav Sorathaiya</option>
                                                <option value="861">Vaishnav Vania</option>
                                                <option value="219">Vaishnava</option>
                                                <option value="220">Vaishya</option>
                                                <option value="221">Vaishya Vani</option>
                                                <option value="1047">Valar</option>
                                                <option value="350">Valluvan</option>
                                                <option value="222">Valmiki</option>
                                                <option value="1015">Valsad</option>
                                                <option value="934">Vani</option>
                                                <option value="877">Vani / Vaishya</option>
                                                <option value="223">Vania</option>
                                                <option value="730">Vanika Vyshya</option>
                                                <option value="224">Vaniya</option>
                                                <option value="902">Vaniya Chettiar</option>
                                                <option value="225">Vanjara</option>
                                                <option value="226">Vanjari</option>
                                                <option value="227">Vankar</option>
                                                <option value="228">Vannar</option>
                                                <option value="229">Vannia Kula Kshatriyar</option>
                                                <option value="1064">Vanyakulakshatriya</option>
                                                <option value="351">Variar</option>
                                                <option value="352">Varshney</option>
                                                <option value="878">Varshney (Barahseni)</option>
                                                <option value="230">Veera Saivam</option>
                                                <option value="937">Veerakodi Vellala</option>
                                                <option value="353">Velaan</option>
                                                <option value="231">Velama</option>
                                                <option value="354">Velanadu Brahmin </option>
                                                <option value="1043">Vellala Pillai</option>
                                                <option value="232">Vellalar</option>
                                                <option value="903">Vellan Chettiars</option>
                                                <option value="233">Veluthedathu Nair</option>
                                                <option value="355">Vettuva Gounder</option>
                                                <option value="996">Vettuvan</option>
                                                <option value="879">Vijayvargia</option>
                                                <option value="821">Vilakithala Nair</option>
                                                <option value="234">Vilakkithala Nair</option>
                                                <option value="236">Vishwakarma</option>
                                                <option value="235">Viswabrahmin</option>
                                                <option value="237">Vokkaliga</option>
                                                <option value="266">Vyas Brahmin </option>
                                                <option value="238">Vysya</option>
                                                <option value="239">Yadav</option>
                                                <option value="819">Yadava Naidu</option>
                                                <option value="357">Yellapu</option>
                                                <option value="999">Others</option>
                                                <option value="0">Don't wish to specify</option>
                                                </select>
                                            </div>
                                            <div class="col-md-6 form-group">
                                                <label class="lb">Sub Caste:</label>
                                                <input type="text" class="form-control" id="subcaste"
                                                    placeholder="Sub Caste" name="msubcaste" >
                                            </div>
                                            </div>
                                        <div class="row">
                                            <div class="col-md-6 form-group">
                                                <label class="lb">Gotharam:</label>
                                                <input type="text" class="form-control" id="gotharam"
                                                    placeholder="Gotharam" name="mgotharam" maxlength="10">
                                            </div>
                                            <div class="col-md-6 form-group">
                                                <label class="lb">Dosham:</label>
                                                <input type="text" class="form-control" id="dosham"
                                                    placeholder="Dosham" name="mdosham">
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6 form-group">
                                                <label class="lb">Education:</label>
                                            <select type="text" class="form-control" name="meducation" id="education"
                                                required>
                                                <option value="">Select</option>
                                                    <option value="Aeronautical">Aeronautical Engineering</option>
                                                    <option value="B.Arch">B.Arch</option>
                                                    <option value="BCA">BCA</option>
                                                    <option value="BE">BE</option>
                                                    <option value="B.Plan">B.Plan</option>
                                                    <option value="B.Sc IT/ Computer Science">B.Sc IT/ Computer Science</option>
                                                    <option value="B.Tech.">B.Tech.</option>
                                                    <option value="M.Arch.">M.Arch.</option>
                                                    <option value="MCA">MCA</option>
                                                    <option value="ME">ME</option>
                                                    <option value="M.Sc. IT / Computer Science">M.Sc. IT / Computer Science</option>
                                                    <option value="M.S.(Engg.)">M.S.(Engg.)</option>
                                                    <option value="M.Tech.">M.Tech.</option>
                                                    <option value="PGDCA">PGDCA</option>
                                                    <option value="B.A.">B.A.</option>
                                                    <option value="B.Com.">B.Com.</option>
                                                    <option value="B.Ed.">B.Ed.</option>
                                                    <option value="BFA">BFA</option>
                                                    <option value="BFT">BFT</option>
                                                    <option value="BLIS">BLIS</option>
                                                    <option value="B.M.M.">B.M.M.</option>
                                                    <option value="B.Sc.">B.Sc.</option>
                                                    <option value="B.S.W">B.S.W</option>
                                                    <option value="B.Phil.">B.Phil.</option>
                                                    <option value="M.A.">M.A.</option>
                                                    <option value="MCom">MCom</option>
                                                    <option value="M.Ed.">M.Ed.</option>
                                                    <option value="MFA">MFA</option>
                                                    <option value="MLIS">MLIS</option>
                                                    <option value="M.Sc.">M.Sc.</option>
                                                    <option value="MSW">MSW</option>
                                                    <option value="M.Phil.">M.Phil.</option>
                                                    <option value="35">BBA</option>
                                                    <option value="65">BFM (Financial Management)</option>
                                                    <option value="19">BHM (Hotel Management)</option>
                                                    <option value="87">Other Bachelor Degree in Management</option>
                                                    <option value="103">BHA / BHM (Hospital Administration)</option>
                                                    <option value="61">MBA</option>
                                                    <option value="76">MFM (Financial Management)</option>
                                                    <option value="14">MHM (Hotel Management)</option>
                                                    <option value="64">MHRM (Human Resource Management)</option>
                                                    <option value="62">PGDM</option>
                                                    <option value="96">Other Master Degree in Management</option>
                                                    <option value="104">MHA / MHM (Hospital Administration)</option>
                                                    <option value="29">B.A.M.S.</option>
                                                    <option value="25">BDS</option>
                                                    <option value="28">BHMS</option>
                                                    <option value="68">BSMS</option>
                                                    <option value="69">BUMS</option>
                                                    <option value="26">BVSc</option>
                                                    <option value="21">MBBS</option>
                                                    <option value="22">MDS</option>
                                                    <option value="20">MD / MS (Medical)</option>
                                                    <option value="23">MVSc</option>
                                                    <option value="105">MCh</option>
                                                    <option value="106">DNB</option>
                                                    <option value="31">BPharm</option>
                                                    <option value="27">BPT</option>
                                                    <option value="101">B.Sc. Nursing</option>
                                                    <option value="88">Other Bachelor Degree in Medicine</option>
                                                    <option value="30">M.Pharm</option>
                                                    <option value="24">MPT</option>
                                                    <option value="97">Other Master Degree in Medicine</option>
                                                    <option value="72">BGL</option>
                                                    <option value="73">B.L.</option>
                                                    <option value="74">LL.B.</option>
                                                    <option value="90">Other Bachelor Degree in Legal</option>
                                                    <option value="71">LL.M.</option>
                                                    <option value="70">M.L.</option>
                                                    <option value="89">Other Master Degree in Legal</option>
                                                    <option value="36">CA</option>
                                                    <option value="75">CFA (Chartered Financial Analyst)</option>
                                                    <option value="48">CS</option>
                                                    <option value="37">ICWA</option>
                                                    <option value="91">Other Degree in Finance</option>
                                                    <option value="77">IAS</option>
                                                    <option value="80">IES</option>
                                                    <option value="81">IFS</option>
                                                    <option value="79">IRS</option>
                                                    <option value="78">IPS</option>
                                                    <option value="92">Other Degree in Service</option>
                                                    <option value="33">Ph.D.</option>
                                                    <option value="107">DM</option>
                                                    <option value="108">Postdoctoral fellow</option>
                                                    <option value="109">Fellow of National Board (FNB)</option>
                                                    <option value="46">Diploma</option>
                                                    <option value="82">Polytechnic</option>
                                                    <option value="45">Trade School</option>
                                                    <option value="94">Others in Diploma</option>
                                                    <option value="47">Higher Secondary School / High School</option>
                                            </select>
                                            </div>
                                            <div class="col-md-6 form-group">
                                                <label class="lb">Age:</label>
                                                <select class="form-select chosen-select" name="mage">
                                                    <option value="">Select Age</option>
                                                    <option value="1">18 to 25</option>
                                                    <option value="2">26 to 33</option>
                                                    <option value="3">34 to 40</option>
                                                    <option value="4">40 to 50</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6 form-group">
                                                <label class="lb">Job:</label>
                                                 <select class="form-select chosen-select" data-placeholder="Select your Profession" name="mjob">
                                                    <option value="Business">Business</option>
                                                    <option value="Employee">Employee</option>
                                                    <option value="Government">Government</option>
                                                    <option value="jobless">Jobless</option>
                                                  </select>
                                            </div>
                                            <div class="col-md-6 form-group">
                                                <label class="lb">Salary:</label>
                                                <input type="number" class="form-control" id="salary"
                                                    placeholder="Salary" name="msalary">
                                            </div>
                                        </div>
                                        <div class="row">
                                                <div class="col-md-6 form-group">
                                                    <label class="lb">Eating Habit</label>
                                                <select class="form-select chosen-select" data-placeholder="Select" name="meating">
                                                 <option value="">Select</option>
                                                 <option value="Vegetarian">Vegetarian</option>
                                                <option value="Non Vegetarian">Non Vegetarian</option>
                                                <option value="Eggetarian">Eggetarian</option>
                                                 </select>
                                                </div>
                                                <div class="col-md-6 form-group">
                                                    <label class="lb">Drinks Habit</label>
                                                <select class="form-select chosen-select" data-placeholder="Select" name="mdrinking">
                                                <option value="">Select</option>
                                                 <option value="No">No</option>
                                                <option value="Drinks Socially">Drinks Socially</option>
                                                <option value="Yes">Yes</option>
                                                </select>
                                                </div>
                                            </div>
                                             <div class="row">
                                                <div class="col-md-6 form-group">
                                                    <label class="lb">Smoking Habit</label>
                                                <select class="form-select chosen-select" data-placeholder="Select your Hobbies" name="msmoking">
                                                 <option value="">Select</option>
                                                 <option value="No">No</option>
                                                <option value="Occasionally">Occasionally</option>
                                                <option value="Yes">Yes</option>
                                                 </select>
                                                </div>
                                                <div class="col-md-6 form-group">
                                                    <label class="lb">Hobbies</label>
                                                <select class="form-select chosen-select" data-placeholder="Select your Hobbies" name="mhobbies">
                                                <option>Select your Hobbies</option>
                                                        <option value="Modelling">Modelling</option>
                                                        <option value="Nature Watching">Nature Watching</option>
                                                        <option value="Movies">Movies</option>
                                                        <option value="Playing">Playing</option>
                                                        <option value="Hangout with family">Hangout with family</option>
                                                        <option value="Adventure travel">Adventure travel</option>
                                                        <option value="Books reading">Books reading</option>
                                                        <option value="Music">Music</option>
                                                        <option value="Cooking">Cooking</option>
                                                        <option value="Yoga">Yoga</option>
                                                </select>
                                                </div>
                                            </div>
                                            <div class="row">
                                            <div class="col-md-6 form-group">
                                                <label class="lb">Star</label>
                                                <select type="text" class="form-control" name="mstar"
                                                id="star" required>
                                                <option value="">Select</option>
                                                <option value="Aries">Aries</option>
                                                <option value="Taurus">Taurus</option>
                                                <option value="Gemini">Gemini</option>
                                                <option value="Cancer">Cancer</option>
                                                <option value="Leo">Leo</option>
                                                <option value="Virgo">Virgo</option>
                                                <option value="Libra">Libra</option>
                                                <option value="Scorpio">Scorpio</option>
                                                <option value="Sagittarius">Sagittarius</option>
                                                <option value="Capricorn">Capricorn</option>
                                                <option value="Aquarius">Aquarius</option>
                                                <option value="Pisces">Pisces</option>
                                                
                                            </select>
                                            </div>
                                            <div class="col-md-6 form-group">
                                               <label class="lb">Raasi</label>
                                                <select type="text" class="form-control" name="mraasi"
                                                id="raasi" required>
                                                <option value="">Select</option>
                                                <option value="Asvini">Asvini</option>
                                                <option value="Baraṇi">Baraṇi</option>
                                                <option value="Karthigai">Karthigai</option>
                                                <option value="Rohini">Rohini</option>
                                                <option value="Mirugasiridam">Mirugasiridam</option>
                                                <option value="Tiruvadirai">Tiruvadirai</option>
                                                <option value="Punarpusam">Punarpusam</option>
                                                <option value="Pusam">Pusam</option>
                                                <option value="Ayilyam">Ayilyam</option>
                                                <option value="Puram">Puram</option>
                                                <option value="Uttiram">Uttiram</option>
                                                <option value="Asttam">Asttam</option>
                                                <option value="Cittirai">Cittirai</option>
                                                <option value="Suvati">Suvati</option>
                                                <option value="Visakam">Visakam</option>
                                                <option value="Anusham">Anusham</option>
                                                <option value="Kettai">Kettai</option>
                                                <option value="Mulam">Mulam</option>
                                                <option value="Puratam">Puratam</option>
                                                <option value="Uttiratam">Uttiratam</option>
                                                <option value="Tiruvonam">Tiruvonam</option>
                                                <option value="Avittam">Avittam</option>
                                                <option value="Sadayam">Sadayam</option>
                                                <option value="Purattadi">Purattadi</option>
                                                <option value="Uttirattadi">Uttirattadi</option>
                                                <option value="Revati">Revati</option>
                                                


                                            </select>
                                            
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-primary">Find Matches</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

               
            </div>
        </div>
    </section>

@endsection